name: soulfood
favicon: null
layout_spectrum: 0.4566708607599139
typography_spectrum: 0.6575302358251065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9259500715415925
  lightness: 0.05116888973861933
  saturation: 0.15456762118265033
  rhythmicContrast: 0.22107213409617543
purpose: []
